[package]
name = "datapack"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "An easy way to create Minecraft datapacks in rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.2"